import { Language, AlertLevel, AlertSchedule } from './types';

export const translations: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    title: "Intelligent Early Warning System",
    dashboard: "Dashboard",
    uploadDocument: "Upload Document",
    uploadAndProcess: "Upload & Process",
    processingDocument: "Processing Document...",
    dropFileHere: "Drop document image here, or click to select",
    allDocumentsUpToDate: "All documents are up to date.",
    employee: "Employee",
    documentType: "Document Type",
    expiresOn: "Expires On",
    status: "Status",
    daysLeft: "days left",
    expired: "Expired",
    expiresIn: "Expires in",
    upcomingExpirations: "Upcoming Expirations & Alerts",
    noUpcomingExpirations: "No upcoming expirations in the next 120 days.",
    visa: "Visa",
    emiratesId: "Emirates ID",
    khdaPermit: "KHDA Teaching Permit",
    contract: "Contract",
    workPermit: "Work Permit",
    medicalFitness: "Medical Fitness Certificate",
    attestedDegree: "Attested Degree",
    healthInsurance: "Health Insurance",
    studentPassport: "Student Passport & Visa",
    unknown: "Unknown",
    allCampuses: "All 37 Dubai Campuses",
    campusFilter: "School Campus",
    khdaComplianceScore: "KHDA Audit Readiness Score",
    totalTeachersStaff: "Tracked Teachers & Staff",
    expiring30Days: "Critical Fines Risk (<30 Days)",
    fastEnrollmentModule: "Rapid Student Transfer / Enrollment Intake",
    errorProcessing: "Error processing document. Please try again.",
    errorUnsupportedFormat: "Unsupported file format. Please upload a JPEG, PNG, or WEBP file.",
    errorParsing: "Could not extract valid information from the document. Please ensure the image is clear.",
    customizeAlerts: "Customize Alerts",
    alertSettings: "Alert Settings",
    documentTypeSettings: "Settings for",
    addRule: "Add Rule",
    daysBeforeExpiration: "Days Before",
    alertLevel: "Alert Level",
    messageTemplate: "Message Template",
    recipients: "Recipients (comma-separated)",
    notificationChannels: "Channels",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    deleteRule: "Delete Rule",
    email: "Email",
    sms: "SMS",
    automatedCall: "Automated Call",
    calendarTask: "Calendar Task",
    // Additional Comprehensive UI Strings
    searchPlaceholder: "⌘K Quick search teachers, documents...",
    aiScan: "AI Scan",
    earlyWarningAlerts: "Early Warning Alerts",
    activeAlerts: "Active Alerts",
    navigation: "Navigation",
    aiQuickActions: "AI Quick Actions",
    aiDocScan: "AI Document Scan",
    satiCopilot: "SATI Copilot AI",
    alertRules: "Alert Rules",
    khdaReady: "✓ KHDA Ready",
    in37Campuses: "in 37 Dubai Campuses",
    realtimeKHDASync: "Real-time KHDA Sync",
    fineRiskZero: "Zero Fine Risk $0",
    immediateActionRequired: "Immediate action required",
    activeIntake: "Active Intake",
    studentTransferModule: "Rapid Student Transfer Intake Module",
    documentMatrixTab: "📄 Document Matrix",
    alertCenterTab: "🔔 Alert Center",
    campuses37Tab: "🏫 37 Dubai Campuses",
    filterStaffOrVisas: "Filter staff or visas...",
    realtimeRecords: "real-time KHDA compliance records",
    action: "Action",
    manageRenewal: "Manage Renewal",
    viewDetail: "View Details",
    viewRecord: "View File",
    totalRegDocs: "Total Regulated Documents",
    inOrderKHDA: "✓ 96.4% KHDA Compliant",
    criticalTeacherPermits: "Critical Teacher Permits",
    expiring30dAlert: "🚨 Expiring <30d Alert",
    visasInProcessing: "Visas in Processing",
    notificationSent: "⚠️ Notification Sent",
    attestedDegreesValidated: "Attested Degrees Validated",
    ministryAccreditation: "Ministry of Education Accreditation",
    matrixTitle: "KHDA Regulatory Compliance Document Matrix",
    matrixSubtitle: "Viewer for Teaching Permits, Residence Visas, Emirates ID, and Attestations across 37 Campuses",
    filterAll: "All",
    filterKHDA: "KHDA Permit",
    filterVisa: "Visa",
    filterEmiratesID: "Emirates ID",
    filterMedical: "Medical Fitness",
    filterDegree: "Attested Degree",
    registeredAlerts: "registered alerts",
    recipientsLabel: "Recipients",
    draftRedoAIMessage: "Draft / Redo AI Message →",
    autoAlertRules: "Automatic Alert Rules",
    autoAlertDesc: "SATI sends automated notifications 120, 90, 60, 30, 15, and 7 days in advance via Email, SMS, and automated calls.",
    customizeThresholds: "Customize Alert Thresholds",
    campusesNetworkTitle: "Network of 37 School Campuses in Dubai",
    campusesNetworkSubtitle: "Real-time monitoring of KHDA compliance, fine risk, and active teaching staff",
    activeCampusesBadge: "37 Active Campuses",
    outstandingScore: "KHDA: Outstanding (98.4%)",
    teachingStaffCount: "42 Teaching Staff",
    zeroFines: "0 Fines",
    auditCampusWithAI: "Audit Campus with AI",
    totalTeachersStaffCard: "Total Teachers & Staff",
    registered37Campuses: "✓ Registered in 37 Campuses",
    khdaApprovalRate: "KHDA Approval Rate",
    teachingPermitsApproved: "Teaching Permits Approved",
    requiredRenewals: "Required Renewals",
    aiNotifsSent: "⚠️ AI Notifications Sent",
    registeredKHDADocs: "Registered KHDA Documents:",
    uploadOCR: "Upload OCR",
    wsLiveActive: "Active Bidirectional WebSocket Connection",
    connectedGemini: "Connected with Gemini Live API",
    scanDocument: "Scan Document",
    khdaReport: "KHDA Report",
    wsStreamTooltip: "Toggle WebSocket Live Stream & HTTP REST",
    streamingText: "Gemini Live AI streaming in real-time...",
    askPlaceholder: "Ask Gemini Live via WebSocket...",
    send: "Send",
    ocrSubtitle: "Google Gemini AI OCR & Campus Assignment",
    assignCampus: "🏫 Assign to Dubai Campus:",
    supportedFormats: "Supports Visa, Emirates ID, KHDA Permit, Medical Fitness (JPEG, PNG, WEBP)",
    khdaComplianceRecord: "KHDA Compliance Record",
    expiryDateLabel: "Expiration Date",
    riskStatusLabel: "Risk Status",
    expiredRiskText: "Expired (KHDA Fine Risk)",
    criticalRiskText: "Expires in {days} days (Attention)",
    validRiskText: "Valid ({days} days left)",
    refNumber: "Ref / File No.",
    regulatoryValidation: "Regulatory Validation",
    verifiedSATI: "SATI Verified",
    uploadNewVersion: "Upload New Version or Scan OCR",
    consultCopilotDrawer: "Consult with Copilot AI in Drawer",
    draftModalTitle: "Draft AI Notification",
    draftModalSubtitle: "Customize and redo the message sent to",
    sentChannelLabel: "Notification Channel Sent:",
    aiDraftedMessage: "AI Drafted Message",
    redoWithGemini: "Redo with Gemini AI",
    redoing: "Redoing...",
    optimizingFor: "Optimizing message for",
    livePreview: "DISPATCH LIVE PREVIEW",
    webhookReady: "Webhook Ready",
    waitingMsgGen: "Waiting for message generation...",
    notifResentSuccess: "Notification successfully resent via",
    sendingNotifBy: "Send Notification via",
    sending: "Sending...",
    tagline: "SATI AI • 24/7 Early Warning Hub",
    heroTitleMain: "Intelligent Monitoring for ",
    heroTitleGradient: "KHDA Permits & Visas",
    heroDesc: "Track expiration dates, teaching permits, and staff records across Dubai 37 Campuses with instant Gemini AI document OCR.",
    heroInputPlaceholder: "Ask SATI Copilot (e.g. 'Which teachers have KHDA permits expiring soon?')...",
    askAI: "Ask AI",
    quickShortcuts: "Quick Shortcuts:",
    criticalAlertsCount: "Critical Alerts",
    khdaAuditChip: "KHDA Audit (96.4%)",
    khdaReportQuery: "Generate KHDA audit report and compliance status",
    scannedTeacher: "Scanned Staff Member"
  },
  [Language.ES]: {
    title: "Sistema de Alerta Temprana Inteligente",
    dashboard: "Panel de Control",
    uploadDocument: "Subir Documento",
    uploadAndProcess: "Subir y Procesar",
    processingDocument: "Procesando Documento...",
    dropFileHere: "Arrastre la imagen del documento aquí, o haga clic para seleccionar",
    allDocumentsUpToDate: "Todos los documentos están al día.",
    employee: "Empleado",
    documentType: "Tipo de Documento",
    expiresOn: "Vence el",
    status: "Estado",
    daysLeft: "días restantes",
    expired: "Vencido",
    expiresIn: "Vence en",
    upcomingExpirations: "Próximos Vencimientos y Alertas",
    noUpcomingExpirations: "No hay vencimientos en los próximos 120 días.",
    visa: "Visa",
    emiratesId: "Emirates ID",
    khdaPermit: "Permiso Docente KHDA",
    contract: "Contrato",
    workPermit: "Permiso de Trabajo",
    medicalFitness: "Aptitud Médica / Salud",
    attestedDegree: "Título Universitario Apostillado",
    healthInsurance: "Seguro Médico",
    studentPassport: "Pasaporte / Visa Estudiante",
    unknown: "Desconocido",
    allCampuses: "Los 37 Campus de Dubái",
    campusFilter: "Campus Escolar",
    khdaComplianceScore: "Índice de Auditoría KHDA",
    totalTeachersStaff: "Docentes y Personal Rastreado",
    expiring30Days: "Riesgo Multas Críticas (<30 Días)",
    fastEnrollmentModule: "Ingreso Rápido de Traslados de Estudiantes",
    errorProcessing: "Error procesando el documento. Por favor, intente de nuevo.",
    errorUnsupportedFormat: "Formato de archivo no soportado. Por favor, suba un archivo JPEG, PNG, o WEBP.",
    errorParsing: "No se pudo extraer información válida del documento. Asegúrese de que la imagen sea clara.",
    customizeAlerts: "Personalizar Alertas",
    alertSettings: "Configuración de Alertas",
    documentTypeSettings: "Configuración para",
    addRule: "Añadir Regla",
    daysBeforeExpiration: "Días Antes",
    alertLevel: "Nivel de Alerta",
    messageTemplate: "Plantilla de Mensaje",
    recipients: "Destinatarios (separados por coma)",
    notificationChannels: "Canales",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    deleteRule: "Eliminar Regla",
    email: "Email",
    sms: "SMS",
    automatedCall: "Llamada Automática",
    calendarTask: "Tarea de Calendario",
    // Additional Comprehensive UI Strings
    searchPlaceholder: "⌘K Buscar docentes, documentos...",
    aiScan: "Escanear IA",
    earlyWarningAlerts: "Alertas Tempranas KHDA",
    activeAlerts: "Activas",
    navigation: "Navegación",
    aiQuickActions: "Acciones Inteligentes",
    aiDocScan: "Escáner OCR IA",
    satiCopilot: "Asistente SATI Copilot",
    alertRules: "Reglas de Alerta",
    khdaReady: "✓ KHDA Listo",
    in37Campuses: "en los 37 campus",
    realtimeKHDASync: "Sincronización en tiempo real KHDA",
    fineRiskZero: "Riesgo Multa $0",
    immediateActionRequired: "Acción inmediata requerida",
    activeIntake: "Ingreso Activo",
    studentTransferModule: "Módulo de traslados rápido de estudiantes",
    documentMatrixTab: "📄 Matriz de Documentos",
    alertCenterTab: "🔔 Centro de Alertas",
    campuses37Tab: "🏫 37 Campus Dubái",
    filterStaffOrVisas: "Filtrar docentes o visas...",
    realtimeRecords: "registros de cumplimiento KHDA en tiempo real",
    action: "Acción",
    manageRenewal: "Gestionar Renovación",
    viewDetail: "Ver Detalle",
    viewRecord: "Ver Expediente",
    totalRegDocs: "Total Documentos Regulación",
    inOrderKHDA: "✓ 96.4% En Regla KHDA",
    criticalTeacherPermits: "Permisos Docentes Críticos",
    expiring30dAlert: "🚨 Alerta Vencimiento <30d",
    visasInProcessing: "Visados en Trámite",
    notificationSent: "⚠️ Notificación Enviada",
    attestedDegreesValidated: "Títulos Apostillados Validados",
    ministryAccreditation: "Acreditación Ministerio Educación",
    matrixTitle: "Matriz Documental de Cumplimiento Normativo KHDA",
    matrixSubtitle: "Visualizador de Permisos Docentes, Visados de Residencia, Emirates ID y Apostillas en los 37 Campus",
    filterAll: "Todos",
    filterKHDA: "Permiso KHDA",
    filterVisa: "Visa",
    filterEmiratesID: "Emirates ID",
    filterMedical: "Aptitud Médica",
    filterDegree: "Título Apostillado",
    registeredAlerts: "alertas registradas",
    recipientsLabel: "Destinatarios",
    draftRedoAIMessage: "Redactar / Rehacer Mensaje IA →",
    autoAlertRules: "Reglas de Alerta Automática",
    autoAlertDesc: "SATI envía avisos automáticos a los 120, 90, 60, 30, 15 y 7 días de anticipación por correo, SMS y llamadas automatizadas.",
    customizeThresholds: "Personalizar Umbrales de Alerta",
    campusesNetworkTitle: "Red de 37 Campus Escolares en Dubái",
    campusesNetworkSubtitle: "Supervisión en tiempo real de cumplimiento KHDA, riesgo de multas y docentes activos",
    activeCampusesBadge: "37 Campus Activos",
    outstandingScore: "KHDA: Outstanding (98.4%)",
    teachingStaffCount: "42 Personal Docente",
    zeroFines: "0 Multas",
    auditCampusWithAI: "Auditar Campus con IA",
    totalTeachersStaffCard: "Total Docentes & Personal",
    registered37Campuses: "✓ Registrados en 37 Campus",
    khdaApprovalRate: "Índice Aprobación KHDA",
    teachingPermitsApproved: "Permisos de Enseñanza Aprobados",
    requiredRenewals: "Renovaciones Requeridas",
    aiNotifsSent: "⚠️ Notificaciones IA Enviadas",
    registeredKHDADocs: "Documentos KHDA Registrados:",
    uploadOCR: "Subir OCR",
    wsLiveActive: "Conexión WebSocket Bidireccional Activa",
    connectedGemini: "Conectado con Gemini Live API",
    scanDocument: "Escanear Documento",
    khdaReport: "Reporte KHDA",
    wsStreamTooltip: "Alternar entre WebSocket Live Stream y HTTP REST",
    streamingText: "Gemini Live AI transmitiendo en tiempo real...",
    askPlaceholder: "Escribe una pregunta a Gemini Live WebSocket...",
    send: "Enviar",
    ocrSubtitle: "Google Gemini AI OCR & Asignación a Campus",
    assignCampus: "🏫 Asignar a Campus Dubái:",
    supportedFormats: "Soporta Visa, Emirates ID, Permiso KHDA, Aptitud Médica (JPEG, PNG, WEBP)",
    khdaComplianceRecord: "Expediente KHDA & Cumplimiento",
    expiryDateLabel: "Fecha de Vencimiento",
    riskStatusLabel: "Estado de Riesgo",
    expiredRiskText: "Vencido (Riesgo Multa KHDA)",
    criticalRiskText: "Vence en {days} días (Atención)",
    validRiskText: "Vigente ({days} días restantes)",
    refNumber: "Ref / Expediente No.",
    regulatoryValidation: "Validación Normativa",
    verifiedSATI: "Verificado SATI",
    uploadNewVersion: "Cargar Nueva Versión o Escanear OCR",
    consultCopilotDrawer: "Consultar con Copilot IA en el Cajón",
    draftModalTitle: "Redactar Notificación con IA",
    draftModalSubtitle: "Personaliza y rehace el mensaje enviado a",
    sentChannelLabel: "Canal de Notificación Enviado:",
    aiDraftedMessage: "Mensaje Redactado por IA",
    redoWithGemini: "Rehacer con Gemini IA",
    redoing: "Rehaciendo...",
    optimizingFor: "Optimizando mensaje para",
    livePreview: "VISTA PREVIA DEL ENVÍO",
    webhookReady: "Webhook Listo",
    waitingMsgGen: "Esperando generación de mensaje...",
    notifResentSuccess: "Notificación reenviada exitosamente a través del canal",
    sendingNotifBy: "Enviar Notificación por",
    sending: "Enviando...",
    tagline: "SATI AI • Sistema de Alerta Temprana 24/7",
    heroTitleMain: "Monitoreo Inteligente de ",
    heroTitleGradient: "Cumplimiento KHDA & Visados",
    heroDesc: "Supervisa la vigencia de documentos, contratos docentes y matrículas en los 37 campus de Dubái con extracción instantánea de OCR por IA Gemini.",
    heroInputPlaceholder: "Pregúntale a SATI Copilot (ej. \"¿Cuáles docentes tienen visa por vencer en 30 días?\")...",
    askAI: "Consultar IA",
    quickShortcuts: "Acciones Rápidas:",
    criticalAlertsCount: "Alertas Críticas",
    khdaAuditChip: "Auditoría KHDA (96.4%)",
    khdaReportQuery: "Generar informe de auditoría KHDA y estado de cumplimiento",
    scannedTeacher: "Docente / Personal Escaneado"
  },
  [Language.AR]: {
    title: "SATI - نظام الإنذار المبكر الذكي",
    dashboard: "لوحة التحكم",
    uploadDocument: "تحميل وثيقة",
    uploadAndProcess: "تحميل ومعالجة",
    processingDocument: "جاري معالجة الوثيقة...",
    dropFileHere: "اسحب صورة الوثيقة هنا، أو انقر للاختيار",
    allDocumentsUpToDate: "جميع الوثائق محدثة ولا يوجد انتهاء صلاحية قريب.",
    employee: "الموظف / المعلم",
    documentType: "نوع الوثيقة",
    expiresOn: "تاريخ الانتهاء",
    status: "الحالة",
    daysLeft: "أيام متبقية",
    expired: "منتهية الصلاحية",
    expiresIn: "تنتهي خلال",
    upcomingExpirations: "التنبيهات والانتهاءات القادمة",
    noUpcomingExpirations: "لا توجد انتهاءات قادمة خلال 120 يوماً.",
    visa: "تأشيرة إقامة (Visa)",
    emiratesId: "الهوية الإماراتية (Emirates ID)",
    khdaPermit: "تصريح التدريس (KHDA)",
    contract: "عقد العمل",
    workPermit: "تصريح العمل",
    medicalFitness: "شهادة اللياقة الطبية",
    attestedDegree: "الشهادة الأكاديمية المصدقة",
    healthInsurance: "التأمين الصحي",
    studentPassport: "جواز / تأشيرة الطالب",
    unknown: "غير معروف",
    allCampuses: "جميع مجمعات دبي الـ 37",
    campusFilter: "المجمع المدرسي",
    khdaComplianceScore: "جاهزية التدقيق للـ KHDA",
    totalTeachersStaff: "إجمالي المعلمين والكادر الأجنبي",
    expiring30Days: "خطر الغرامات الحرجة (أقل من 30 يوماً)",
    fastEnrollmentModule: "وحدة التسجيل ونقل الطلاب السريع",
    errorProcessing: "حدث خطأ أثناء معالجة الوثيقة. يرجى المحاولة مرة أخرى.",
    errorUnsupportedFormat: "صيغة الملف غير مدعومة. يرجى تحميل ملف JPEG أو PNG أو WEBP.",
    errorParsing: "تعذر استخراج معلومات صالحة من الوثيقة. يرجى التأكد من وضوح الصورة.",
    customizeAlerts: "تخصيص التنبيهات",
    alertSettings: "إعدادات التنبيهات الذكية",
    documentTypeSettings: "إعدادات وثيقة",
    addRule: "إضافة قاعدة تنبيه",
    daysBeforeExpiration: "الأيام قبل الانتهاء",
    alertLevel: "مستوى التنبيه",
    messageTemplate: "قالب الرسالة",
    recipients: "المستلمون (مفصولين بفواصل)",
    notificationChannels: "قنوات الإشعارات",
    saveChanges: "حفظ التغييرات",
    cancel: "إلغاء",
    deleteRule: "حذف القاعدة",
    email: "البريد الإلكتروني",
    sms: "رسالة نصية SMS",
    automatedCall: "مكالمة آلية",
    calendarTask: "مهمة تقويم",
    // Additional Comprehensive UI Strings
    searchPlaceholder: "K⌘ بحث سريع عن المعلمين والوثائق...",
    aiScan: "مسح ذكي",
    earlyWarningAlerts: "تنبيهات KHDA المبكرة",
    activeAlerts: "نشطة",
    navigation: "التصفح الرئيسي",
    aiQuickActions: "أدوات الذكاء الاصطناعي",
    aiDocScan: "مسح الوثائق بالذكاء الاصطناعي",
    satiCopilot: "مساعد SATI الذكي",
    alertRules: "إعدادات القواعد",
    khdaReady: "جاهز للـ KHDA ✓",
    in37Campuses: "في 37 مجمعاً",
    realtimeKHDASync: "مزامنة فورية مع هيئة المعرفة",
    fineRiskZero: "خطر غرامات 0$",
    immediateActionRequired: "مطلوب إجراء عاجل",
    activeIntake: "تسجيل نشط",
    studentTransferModule: "وحدة نقل الطلاب السريعة",
    documentMatrixTab: "📄 مصفوفة الوثائق",
    alertCenterTab: "🔔 مركز التنبيهات",
    campuses37Tab: "🏫 37 مجمعاً بدبي",
    filterStaffOrVisas: "تصفية المعلمين والتأشيرات...",
    realtimeRecords: "سجلات امتثال KHDA مباشرة",
    action: "الإجراء",
    manageRenewal: "إدارة التجديد",
    viewDetail: "عرض التفاصيل",
    viewRecord: "عرض الملف",
    totalRegDocs: "إجمالي الوثائق التنظيمية",
    inOrderKHDA: "✓ 96.4% متوافق مع KHDA",
    criticalTeacherPermits: "تصاريح المعلمين الحرجة",
    expiring30dAlert: "🚨 تنبيه انتهاء أقل من 30 يوم",
    visasInProcessing: "تأشيرات قيد المعالجة",
    notificationSent: "⚠️ تم إرسال الإشعار",
    attestedDegreesValidated: "الشهادات المصدقة المعتمدة",
    ministryAccreditation: "اعتماد وزارة التربية والتعليم",
    matrixTitle: "مصفوفة الوثائق للامتثال التنظيمي للـ KHDA",
    matrixSubtitle: "استعراض تصاريح التدريس، التأشيرات، الهوية الإماراتية والتصديقات في 37 مجمعاً",
    filterAll: "الكل",
    filterKHDA: "تصريح KHDA",
    filterVisa: "تأشيرة",
    filterEmiratesID: "الهوية الإماراتية",
    filterMedical: "اللياقة الطبية",
    filterDegree: "شهادة مصدقة",
    registeredAlerts: "تنبيهات مسجلة",
    recipientsLabel: "المستلمون",
    draftRedoAIMessage: "صياغة / إعادة صياغة رسالة الذكاء الاصطناعي ←",
    autoAlertRules: "قواعد التنبيه الآلي",
    autoAlertDesc: "يرسل نظام SATI إشعارات تلقائية قبل 120، 90، 60، 30، 15، و 7 أيام عبر البريد الإلكتروني، SMS والمكالمات الآلية.",
    customizeThresholds: "تخصيص حدود التنبيه",
    campusesNetworkTitle: "شبكة مجمعات دبي الـ 37 المدرسية",
    campusesNetworkSubtitle: "مراقبة فورية للامتثال والالتزام وخطر الغرامات والكادر الفعال",
    activeCampusesBadge: "37 مجمعاً نشطاً",
    outstandingScore: "KHDA: ممتاز (98.4%)",
    teachingStaffCount: "42 من الكادر التعليمي",
    zeroFines: "0 غرامات",
    auditCampusWithAI: "تدقيق المجمع بالذكاء الاصطناعي",
    totalTeachersStaffCard: "إجمالي المعلمين والكادر",
    registered37Campuses: "✓ مسجلون في 37 مجمعاً",
    khdaApprovalRate: "نسبة موافقة KHDA",
    teachingPermitsApproved: "تصاريح التدريس المعتمدة",
    requiredRenewals: "التجديدات المطلوبة",
    aiNotifsSent: "⚠️ تم إرسال إشعارات الذكاء الاصطناعي",
    registeredKHDADocs: "وثائق KHDA المسجلة:",
    uploadOCR: "تحميل OCR",
    wsLiveActive: "اتصال WebSocket ثنائي الاتجاه نشط",
    connectedGemini: "متصل بـ Gemini Live API",
    scanDocument: "مسح وثيقة",
    khdaReport: "تقرير KHDA",
    wsStreamTooltip: "التبديل بين WebSocket Live Stream و HTTP REST",
    streamingText: "بث مباشر للذكاء الاصطناعي Gemini...",
    askPlaceholder: "اكتب سؤالاً لـ Gemini Live WebSocket...",
    send: "إرسال",
    ocrSubtitle: "الذكاء الاصطناعي Gemini OCR وتعيين المجمع",
    assignCampus: "🏫 التعيين لمجمع دبي:",
    supportedFormats: "يدعم التأشيرة، الهوية، تصريح KHDA، اللياقة الطبية (JPEG, PNG, WEBP)",
    khdaComplianceRecord: "سجل امتثال KHDA",
    expiryDateLabel: "تاريخ الانتهاء",
    riskStatusLabel: "حالة الخطر",
    expiredRiskText: "منتهي (خطر غرامة KHDA)",
    criticalRiskText: "ينتهي خلال {days} يوماً (انتباه)",
    validRiskText: "سارٍ (متبقي {days} يوماً)",
    refNumber: "رقم المرجع / الملف",
    regulatoryValidation: "التحقق التنظيمي",
    verifiedSATI: "تم التحقق بواسطة SATI",
    uploadNewVersion: "تحميل نسخة جديدة أو مسح OCR",
    consultCopilotDrawer: "استشارة Copilot الذكي في الدرج",
    draftModalTitle: "صياغة إشعار بالذكاء الاصطناعي",
    draftModalSubtitle: "تخصيص وإعادة صياغة الرسالة المرسلة إلى",
    sentChannelLabel: "قناة الإشعار المرسلة:",
    aiDraftedMessage: "الرسالة المصاغة بالذكاء الاصطناعي",
    redoWithGemini: "إعادة صياغة مع Gemini IA",
    redoing: "جاري إعادة الصياغة...",
    optimizingFor: "تحسين الرسالة لـ",
    livePreview: "معاينة الإرسال المباشرة",
    webhookReady: "الويب هوك جاهز",
    waitingMsgGen: "في انتظار صياغة الرسالة...",
    notifResentSuccess: "تم إعادة إرسال الإشعار بنجاح عبر قناة",
    sendingNotifBy: "إرسال الإشعار عبر",
    sending: "جاري الإرسال...",
    tagline: "SATI AI • نظام الإنذار المبكر على مدار الساعة",
    heroTitleMain: "المراقبة الذكية لامتثال ",
    heroTitleGradient: "تأشيرات وتصاريح KHDA",
    heroDesc: "مراقبة صلاحية التأشيرات والعقود في مجمعات دبي الـ 37 مع استخراج فوري بواسطة الذكاء الاصطناعي Gemini.",
    heroInputPlaceholder: "اسأل SATI Copilot (مثال: \"ما هي التأشيرات التي تنتهي خلال 30 يوماً؟\")...",
    askAI: "بحث بالذكاء الاصطناعي",
    quickShortcuts: "إجراءات سريعة:",
    criticalAlertsCount: "تنبيهات حرجة",
    khdaAuditChip: "تدقيق KHDA (96.4%)",
    khdaReportQuery: "إنشاء تقرير تدقيق KHDA وحالة الالتزام",
    scannedTeacher: "معلم / كادر ممسوح ضوئياً"
  }
};

export const INITIAL_ALERT_SCHEDULE: AlertSchedule = {
    'Contract': [
        { id: 'c1', days: 120, level: AlertLevel.Info, message: "FIRST WARNING: Contract ends in 4 months. Start internal renewal talks.", recipients: ['HR', 'Direct Manager'], channels: ['Email', 'Telegram'] },
        { id: 'c2', days: 90, level: AlertLevel.Formal, message: "FORMAL NOTICE: Official contract expiration reminder. Renewal notification required by [Deadline Date].", recipients: ['HR', 'Employee', 'Manager'], channels: ['Email', 'WhatsApp'] },
    ],
    'Visa': [
        { id: 'v1', days: 90, level: AlertLevel.Info, message: "PROCESS START: Your visa/permit expires in 90 days. Renewal process initiated. Please prepare documents [List].", recipients: ['Employee', 'HR'], channels: ['WhatsApp', 'Email'] },
    ],
    'Work Permit': [
        { id: 'wp1', days: 90, level: AlertLevel.Info, message: "PROCESS START: Your visa/permit expires in 90 days. Renewal process initiated. Please prepare documents [List].", recipients: ['Employee', 'HR'], channels: ['Discord', 'Email'] },
    ],
    'Default': [
        { id: 'd1', days: 60, level: AlertLevel.FollowUp, message: "FOLLOW-UP: 60 days remaining. Renewal process should be underway. Any impediments?", recipients: ['Employee', 'HR'], channels: ['Email', 'WhatsApp'] },
        { id: 'd2', days: 30, level: AlertLevel.Medium, message: "MEDIUM ALERT: Attention! Your document expires in 30 days. Renewal should be in its final phase.", recipients: ['Employee', 'HR', 'Manager'], channels: ['WhatsApp', 'Telegram'] },
        { id: 'd3', days: 15, level: AlertLevel.High, message: "HIGH ALERT: URGENT! Your document expires in 15 days. If renewal is not complete, contact HR immediately.", recipients: ['Employee', 'HR', 'Manager'], channels: ['WhatsApp', 'Discord'] },
        { id: 'd4', days: 7, level: AlertLevel.Critical, message: "CRITICAL ALERT: FINAL ALERT! Your document expires in 7 days. Imminent risk of fines and work suspension.", recipients: ['Employee', 'HR', 'Manager', 'Director'], channels: ['Email', 'Phone', 'WhatsApp'] },
    ]
};

export const DUBAI_CAMPUSES = [
  'All 37 Dubai Campuses',
  'Campus 01 - Dubai Marina',
  'Campus 02 - Al Barsha',
  'Campus 03 - Jumeirah',
  'Campus 04 - Silicon Oasis',
  'Campus 05 - Dubai South',
  'Campus 06 - Downtown Dubai',
  'Campus 07 - Academic City',
  'Campus 08 - Arabian Ranches',
];

export const INITIAL_EMPLOYEES = [
  {
    id: 'emp-1',
    name: 'Sarah Jenkins (Math Teacher)',
    campus: 'Campus 01 - Dubai Marina',
    role: 'Teacher',
    documents: [
      { id: 'doc-1', type: 'Visa', expiryDate: '2026-09-14' },
      { id: 'doc-2', type: 'KHDA Permit', expiryDate: '2026-09-08' },
      { id: 'doc-3', type: 'Emirates ID', expiryDate: '2027-02-15' },
      { id: 'doc-4', type: 'Medical Fitness', expiryDate: '2027-05-20' },
      { id: 'doc-5', type: 'Attested Degree', expiryDate: '2029-12-31' },
    ]
  },
  {
    id: 'emp-2',
    name: 'Carlos Mendoza (Science Lead)',
    campus: 'Campus 01 - Dubai Marina',
    role: 'Head of Science',
    documents: [
      { id: 'doc-6', type: 'Visa', expiryDate: '2026-09-14' },
      { id: 'doc-7', type: 'KHDA Permit', expiryDate: '2026-10-10' },
      { id: 'doc-8', type: 'Emirates ID', expiryDate: '2026-11-20' },
    ]
  },
  {
    id: 'emp-3',
    name: 'Tariq Al-Mansoor (Arabic Studies)',
    campus: 'Campus 02 - Al Barsha',
    role: 'Senior Arabic Teacher',
    documents: [
      { id: 'doc-9', type: 'Medical Fitness', expiryDate: '2026-08-31' },
      { id: 'doc-10', type: 'KHDA Permit', expiryDate: '2027-01-15' },
    ]
  },
  {
    id: 'emp-4',
    name: 'Elena Rostova (Music Instructor)',
    campus: 'Campus 03 - Jumeirah',
    role: 'Music Teacher',
    documents: [
      { id: 'doc-11', type: 'Work Permit', expiryDate: '2026-08-30' },
      { id: 'doc-12', type: 'Visa', expiryDate: '2026-09-05' },
    ]
  }
];

