import { Language, AlertLevel, AlertSchedule } from './types';

export const translations: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    title: "Intelligent Early Warning System",
    dashboard: "Dashboard",
    uploadDocument: "Upload Document",
    uploadAndProcess: "Upload & Process",
    processingDocument: "Processing Document...",
    dropFileHere: "Drop document image here, or click to select",
    allDocumentsUpToDate: "All documents are up to date.",
    employee: "Employee",
    documentType: "Document Type",
    expiresOn: "Expires On",
    status: "Status",
    daysLeft: "days left",
    expired: "Expired",
    expiresIn: "Expires in",
    upcomingExpirations: "Upcoming Expirations & Alerts",
    noUpcomingExpirations: "No upcoming expirations in the next 120 days.",
    visa: "Visa",
    emiratesId: "Emirates ID",
    khdaPermit: "KHDA Teaching Permit",
    contract: "Contract",
    workPermit: "Work Permit",
    medicalFitness: "Medical Fitness Certificate",
    attestedDegree: "Attested Degree",
    healthInsurance: "Health Insurance",
    studentPassport: "Student Passport & Visa",
    unknown: "Unknown",
    allCampuses: "All 37 Dubai Campuses",
    campusFilter: "School Campus",
    khdaComplianceScore: "KHDA Audit Readiness Score",
    totalTeachersStaff: "Tracked Teachers & Staff",
    expiring30Days: "Critical Fines Risk (<30 Days)",
    fastEnrollmentModule: "Rapid Student Transfer / Enrollment Intake",
    errorProcessing: "Error processing document. Please try again.",
    errorUnsupportedFormat: "Unsupported file format. Please upload a JPEG, PNG, or WEBP file.",
    errorParsing: "Could not extract valid information from the document. Please ensure the image is clear.",
    customizeAlerts: "Customize Alerts",
    alertSettings: "Alert Settings",
    documentTypeSettings: "Settings for",
    addRule: "Add Rule",
    daysBeforeExpiration: "Days Before",
    alertLevel: "Alert Level",
    messageTemplate: "Message Template",
    recipients: "Recipients (comma-separated)",
    notificationChannels: "Channels",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    deleteRule: "Delete Rule",
    email: "Email",
    sms: "SMS",
    automatedCall: "Automated Call",
    calendarTask: "Calendar Task"
  },
  [Language.ES]: {
    title: "Sistema de Alerta Temprana Inteligente",
    dashboard: "Panel de Control",
    uploadDocument: "Subir Documento",
    uploadAndProcess: "Subir y Procesar",
    processingDocument: "Procesando Documento...",
    dropFileHere: "Arrastre la imagen del documento aquí, o haga clic para seleccionar",
    allDocumentsUpToDate: "Todos los documentos están al día.",
    employee: "Empleado",
    documentType: "Tipo de Documento",
    expiresOn: "Vence el",
    status: "Estado",
    daysLeft: "días restantes",
    expired: "Vencido",
    expiresIn: "Vence en",
    upcomingExpirations: "Próximos Vencimientos y Alertas",
    noUpcomingExpirations: "No hay vencimientos en los próximos 120 días.",
    visa: "Visa",
    emiratesId: "Emirates ID",
    khdaPermit: "Permiso Docente KHDA",
    contract: "Contrato",
    workPermit: "Permiso de Trabajo",
    medicalFitness: "Aptitud Médica / Salud",
    attestedDegree: "Título Universitario Apostillado",
    healthInsurance: "Seguro Médico",
    studentPassport: "Pasaporte / Visa Estudiante",
    unknown: "Desconocido",
    allCampuses: "Los 37 Campus de Dubái",
    campusFilter: "Campus Escolar",
    khdaComplianceScore: "Índice de Auditoría KHDA",
    totalTeachersStaff: "Docentes y Personal Rastreado",
    expiring30Days: "Riesgo Multas Críticas (<30 Días)",
    fastEnrollmentModule: "Ingreso Rápido de Traslados de Estudiantes",
    errorProcessing: "Error procesando el documento. Por favor, intente de nuevo.",
    errorUnsupportedFormat: "Formato de archivo no soportado. Por favor, suba un archivo JPEG, PNG, o WEBP.",
    errorParsing: "No se pudo extraer información válida del documento. Asegúrese de que la imagen sea clara.",
    customizeAlerts: "Personalizar Alertas",
    alertSettings: "Configuración de Alertas",
    documentTypeSettings: "Configuración para",
    addRule: "Añadir Regla",
    daysBeforeExpiration: "Días Antes",
    alertLevel: "Nivel de Alerta",
    messageTemplate: "Plantilla de Mensaje",
    recipients: "Destinatarios (separados por coma)",
    notificationChannels: "Canales",
    saveChanges: "Guardar Cambios",
    cancel: "Cancelar",
    deleteRule: "Eliminar Regla",
    email: "Email",
    sms: "SMS",
    automatedCall: "Llamada Automática",
    calendarTask: "Tarea de Calendario"
  },
  [Language.AR]: {
    title: "SATI - نظام الإنذار المبكر الذكي",
    dashboard: "لوحة التحكم",
    uploadDocument: "تحميل وثيقة",
    uploadAndProcess: "تحميل ومعالجة",
    processingDocument: "جاري معالجة الوثيقة...",
    dropFileHere: "اسحب صورة الوثيقة هنا، أو انقر للاختيار",
    allDocumentsUpToDate: "جميع الوثائق محدثة ولا يوجد انتهاء صلاحية قريب.",
    employee: "الموظف / المعلم",
    documentType: "نوع الوثيقة",
    expiresOn: "تاريخ الانتهاء",
    status: "الحالة",
    daysLeft: "أيام متبقية",
    expired: "منتهية الصلاحية",
    expiresIn: "تنتهي خلال",
    upcomingExpirations: "التنبيهات والانتهاءات القادمة",
    noUpcomingExpirations: "لا توجد انتهاءات قادمة خلال 120 يوماً.",
    visa: "تأشيرة إقامة (Visa)",
    emiratesId: "الهوية الإماراتية (Emirates ID)",
    khdaPermit: "تصريح التدريس (KHDA)",
    contract: "عقد العمل",
    workPermit: "تصريح العمل",
    medicalFitness: "شهادة اللياقة الطبية",
    attestedDegree: "الشهادة الأكاديمية المصدقة",
    healthInsurance: "التأمين الصحي",
    studentPassport: "جواز / تأشيرة الطالب",
    unknown: "غير معروف",
    allCampuses: "جميع مجمعات دبي الـ 37",
    campusFilter: "المجمع المدرسي",
    khdaComplianceScore: "جاهزية التدقيق للـ KHDA",
    totalTeachersStaff: "إجمالي المعلمين والكادر الأجنبي",
    expiring30Days: "خطر الغرامات الحرجة (أقل من 30 يوماً)",
    fastEnrollmentModule: "وحدة التسجيل ونقل الطلاب السريع",
    errorProcessing: "حدث خطأ أثناء معالجة الوثيقة. يرجى المحاولة مرة أخرى.",
    errorUnsupportedFormat: "صيغة الملف غير مدعومة. يرجى تحميل ملف JPEG أو PNG أو WEBP.",
    errorParsing: "تعذر استخراج معلومات صالحة من الوثيقة. يرجى التأكد من وضوح الصورة.",
    customizeAlerts: "تخصيص التنبيهات",
    alertSettings: "إعدادات التنبيهات الذكية",
    documentTypeSettings: "إعدادات وثيقة",
    addRule: "إضافة قاعدة تنبيه",
    daysBeforeExpiration: "الأيام قبل الانتهاء",
    alertLevel: "مستوى التنبيه",
    messageTemplate: "قالب الرسالة",
    recipients: "المستلمون (مفصولين بفواصل)",
    notificationChannels: "قنوات الإشعارات",
    saveChanges: "حفظ التغييرات",
    cancel: "إلغاء",
    deleteRule: "حذف القاعدة",
    email: "البريد الإلكتروني",
    sms: "رسالة نصية SMS",
    automatedCall: "مكالمة آلية",
    calendarTask: "مهمة تقويم"
  }
};

export const INITIAL_ALERT_SCHEDULE: AlertSchedule = {
    'Contract': [
        { id: 'c1', days: 120, level: AlertLevel.Info, message: "FIRST WARNING: Contract ends in 4 months. Start internal renewal talks.", recipients: ['HR', 'Direct Manager'], channels: ['Email'] },
        { id: 'c2', days: 90, level: AlertLevel.Formal, message: "FORMAL NOTICE: Official contract expiration reminder. Renewal notification required by [Deadline Date].", recipients: ['HR', 'Employee', 'Manager'], channels: ['Email (Formal)'] },
    ],
    'Visa': [
        { id: 'v1', days: 90, level: AlertLevel.Info, message: "PROCESS START: Your visa/permit expires in 90 days. Renewal process initiated. Please prepare documents [List].", recipients: ['Employee', 'HR'], channels: ['Email', 'Calendar Task'] },
    ],
    'Work Permit': [
        { id: 'wp1', days: 90, level: AlertLevel.Info, message: "PROCESS START: Your visa/permit expires in 90 days. Renewal process initiated. Please prepare documents [List].", recipients: ['Employee', 'HR'], channels: ['Email', 'Calendar Task'] },
    ],
    'Default': [
        { id: 'd1', days: 60, level: AlertLevel.FollowUp, message: "FOLLOW-UP: 60 days remaining. Renewal process should be underway. Any impediments?", recipients: ['Employee', 'HR'], channels: ['Email'] },
        { id: 'd2', days: 30, level: AlertLevel.Medium, message: "MEDIUM ALERT: Attention! Your document expires in 30 days. Renewal should be in its final phase.", recipients: ['Employee', 'HR', 'Manager'], channels: ['Email', 'SMS'] },
        { id: 'd3', days: 15, level: AlertLevel.High, message: "HIGH ALERT: URGENT! Your document expires in 15 days. If renewal is not complete, contact HR immediately.", recipients: ['Employee', 'HR', 'Manager'], channels: ['Email', 'SMS'] },
        { id: 'd4', days: 7, level: AlertLevel.Critical, message: "CRITICAL ALERT: FINAL ALERT! Your document expires in 7 days. Imminent risk of fines and work suspension.", recipients: ['Employee', 'HR', 'Manager', 'Director'], channels: ['Email', 'SMS', 'Automated Call'] },
    ]
};
